name: Sync multiple branches
on:
  push:
    branches:
      - 'staging'
  workflow_dispatch:
  
jobs:
  test-and-sync:
    name: Test and Sync SCALE Catalog
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/truecharts/devcontainer:v2.6.0@sha256:cefec796e714cd07bae25ef48670999819ceefa0cbb5ff8b9738fabc916ceea7
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        name: Checkout
        with:
          fetch-depth: 1

      - name: catalog tests
        run: |
          echo "Starting Catalog Validation"
          /usr/local/bin/catalog_validate validate --path "${PWD}/catalog"
          
      - uses: actions/checkout@master

      - name: Merge staging -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: staging
          target_branch: main
          github_token: ${{ github.token }}