name: Sync multiple branches

concurrency: catalog-test

on:
  push:
    branches:
      - 'staging'
  workflow_dispatch:

jobs:
  test-and-sync:
    name: Test and Sync SCALE Catalog
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/truecharts/devcontainer:v3.1.1@sha256:b682ca20989c13c4afc8edf0660f83ce8e896e32db21d6321ba06f135911fc81
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        name: Checkout

      - name: catalog tests
        run: |
          echo "Starting Catalog Validation"
          /usr/local/bin/catalog_validate validate --path "${PWD}"

      - name: catalog json generation
        run: |
          echo "Starting Catalog json Generation"
          pwd
          ls -la
          /usr/local/bin/catalog_update update --path "${PWD}"

      - name: Merge staging into main
        run: |
          git config user.name "TrueCharts-Bot"
          git config user.email "bot@truecharts.org"
          pwd
          ls -la
          git add catalog.json || echo "Adding catalog.json failed"
          git commit -m "Commit catalog.json" || echo "Commiting catalog.json failed"
          git push -f origin staging:main
